# fly.toml app configuration file generated for stockprice on 2024-01-18T19:29:26-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stockprice"
primary_region = "yyz"

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
